-- settings-preset-core.lua
-- 装机预设：由装机包生成，来自蓝本设备的实际设置（已剔除隐私/临时数据）。
-- 用法：WorkBuddy 读取此文件，把下列键块合并进目标设备的 settings.reader.lua
--       （同名键整块替换，没有则追加；其余键保持目标设备原值不动）。
-- 注意：此文件本身不会被上传到设备，仅作为合并的数据源。
return {
    ["activate_menu"] = "swipe",
    ["disable_double_tap"] = false, -- 双击手势依赖（蓝本原值）
    ["activate_menu_top"] = "tap",
    ["show_bottom_menu"] = false,
    ["language"] = "zh_CN",
    ["keyboard_layout"] = "zh_CN",
    ["keyboard_layouts"] = {
        [1] = "zh_CN",
    },
    ["keyboard_chinese_pinyin_settings"] = {
        ["show_candi"] = true,
    },
    ["keyboard_key_font_size"] = 22,
    ["home_dir"] = "/mnt/us/BOOKS",
    ["inbox_dir"] = "/mnt/us/BOOKS",
    ["document_metadata_folder"] = "doc",
    ["history_filter"] = "all",
    ["history_freeze_finished_books"] = true,
    ["autoremove_deleted_items_from_history"] = true,
    ["collate"] = "access",
    ["bookmarks_items_per_page"] = 14,
    ["bookmarks_items_text_type"] = "note",
    ["toc_items_per_page"] = 14,
    ["dict_font_size"] = 25,
    ["dict_largewindow"] = true,
    ["dict_button_config"] = {
        ["layout"] = {
            [1] = {
                [1] = "prev_dict",
                [2] = "highlight",
                [3] = "next_dict",
            },
            [2] = {
                [1] = "close",
            },
        },
        ["order"] = {
            [1] = "prev_dict",
            [2] = "highlight",
            [3] = "next_dict",
            [4] = "wikipedia",
            [5] = "search",
            [6] = "close",
            [7] = "translate",
        },
        ["row_count"] = {
            [1] = 3,
            [2] = 3,
        },
    },
    ["dict_presets"] = {
        ["严肃文学"] = {
            ["enabled_dict_names"] = {
                ["中华成语大词典 2.1"] = true,
                ["古汉语常用字字典"] = true,
                ["汉语大词典 离线版"] = true,
                ["现代汉语词典"] = true,
                ["诗词典故词典"] = true,
            },
        },
        ["中国哲学"] = {
            ["enabled_dict_names"] = {
                ["中华成语大词典 2.1"] = true,
                ["佛光大辞典"] = true,
                ["古汉语常用字字典"] = true,
                ["康熙字典文字版"] = true,
                ["汉语大词典 离线版"] = true,
                ["诗词典故词典"] = true,
            },
        },
        ["人文历史"] = {
            ["enabled_dict_names"] = {
                ["中华成语大词典 2.1"] = true,
                ["古汉语常用字字典"] = true,
                ["康熙字典文字版"] = true,
                ["汉语大词典 离线版"] = true,
                ["现代汉语词典"] = true,
                ["诗词典故词典"] = true,
            },
        },
        ["古典文学"] = {
            ["enabled_dict_names"] = {
                ["中华成语大词典 2.1"] = true,
                ["佛光大辞典"] = true,
                ["古汉语常用字字典"] = true,
                ["康熙字典文字版"] = true,
                ["汉语大词典 离线版"] = true,
                ["现代汉语词典"] = true,
                ["诗词典故词典"] = true,
            },
        },
        ["外国名著"] = {
            ["enabled_dict_names"] = {
                ["朗道汉英字典5.0"] = true,
                ["朗道英汉字典5.0"] = true,
                ["汉语大词典 离线版"] = true,
                ["牛津现代英汉双解词典"] = true,
                ["现代汉语词典"] = true,
            },
        },
        ["诗词格律"] = {
            ["enabled_dict_names"] = {
                ["中华成语大词典 2.1"] = true,
                ["古汉语常用字字典"] = true,
                ["康熙字典文字版"] = true,
                ["廣韻"] = true,
                ["廣韻反查"] = true,
                ["汉语大词典 离线版"] = true,
                ["诗词典故词典"] = true,
            },
        },
        ["通俗文学"] = {
            ["enabled_dict_names"] = {
                ["中华成语大词典 2.1"] = true,
                ["汉语大词典 离线版"] = true,
                ["现代汉语词典"] = true,
            },
        },
    },
    ["dicts_order"] = {
        ["data/dict/stardict-chengyuda-2.4.2/chengyuda.ifo"] = 2,
        ["data/dict/stardict-chibigenc-2.4.2/chibigenc.ifo"] = 10,
        ["data/dict/stardict-foguangdacidian-2.4.2/foguangdacidian.ifo"] = 3,
        ["data/dict/stardict-ghycyzzd-2.4.2/ghycyzzd.ifo"] = 4,
        ["data/dict/stardict-guangyun-2.4.2/guangyun.ifo"] = 6,
        ["data/dict/stardict-gyfancha-2.4.2/gyfancha.ifo"] = 7,
        ["data/dict/stardict-kangxitext-2.4.2/kangxitext.ifo"] = 5,
        ["data/dict/stardict-langdao-ce-gb-2.4.2/langdao-ce-gb.ifo"] = 8,
        ["data/dict/stardict-langdao-ec-gb-2.4.2/langdao-ec-gb.ifo"] = 9,
        ["data/dict/stardict-oxford-gb-2.4.2/oxford-gb.ifo"] = 11,
        ["data/dict/stardict-poemstory-2.4.2/poemstory.ifo"] = 12,
        ["data/dict/stardict-xiandaihanyucidian_fix-2.4.2/xiandaihanyucidian_fix.ifo"] = 1,
    },
    ["dicts_disabled"] = {
        ["data/dict/stardict-foguangdacidian-2.4.2/foguangdacidian.ifo"] = true,
        ["data/dict/stardict-guangyun-2.4.2/guangyun.ifo"] = true,
        ["data/dict/stardict-gyfancha-2.4.2/gyfancha.ifo"] = true,
    },
    ["footer"] = {
        ["align"] = "center",
        ["all_at_once"] = false,
        ["auto_refresh_time"] = false,
        ["battery"] = true,
        ["battery_hide_threshold"] = 100,
        ["book_author"] = false,
        ["book_author_max_width_pct"] = 30,
        ["book_chapter"] = false,
        ["book_chapter_max_width_pct"] = 30,
        ["book_time_to_read"] = false,
        ["book_title"] = false,
        ["book_title_max_width_pct"] = 30,
        ["bookmark_count"] = false,
        ["bottom_horizontal_separator"] = false,
        ["chapter_progress"] = false,
        ["chapter_progress_bar"] = false,
        ["chapter_time_to_read"] = false,
        ["container_bottom_padding"] = 1,
        ["container_height"] = 14,
        ["disable_progress_bar"] = true,
        ["disabled"] = false,
        ["frontlight"] = false,
        ["hide_empty_generators"] = false,
        ["initial_marker"] = false,
        ["invert_progress_direction"] = false,
        ["item_prefix"] = "icons",
        ["items_separator"] = "bar",
        ["lock_tap"] = false,
        ["mem_usage"] = false,
        ["page_progress"] = true,
        ["page_turning_inverted"] = false,
        ["pages_left"] = false,
        ["pages_left_book"] = false,
        ["pages_left_includes_current_page"] = false,
        ["percentage"] = false,
        ["progress_bar_min_width_pct"] = 20,
        ["progress_bar_position"] = "alongside",
        ["progress_margin"] = false,
        ["progress_margin_width"] = 10,
        ["progress_pct_format"] = "0",
        ["progress_style_thick_height"] = 7,
        ["progress_style_thin"] = false,
        ["progress_style_thin_height"] = 3,
        ["reclaim_height"] = false,
        ["skim_widget_on_hold"] = false,
        ["text_font_bold"] = false,
        ["text_font_face"] = "./fonts/noto/NotoSans-Regular.ttf",
        ["text_font_size"] = 14,
        ["time"] = true,
        ["toc_markers"] = true,
        ["toc_markers_width"] = 2,
        ["wifi_status"] = false,
    },
    ["reader_footer_custom_text"] = "KOReader",
    ["reader_footer_custom_text_repetitions"] = "1",
    ["reader_footer_mode"] = 0,
    ["copt_b_page_margin"] = 15,
    ["copt_block_rendering_mode"] = 2,
    ["copt_cjk_width_scaling"] = 100,
    ["copt_css"] = "./data/epub.css",
    ["copt_embedded_css"] = 1,
    ["copt_embedded_fonts"] = 1,
    ["copt_font_base_weight"] = 1.5,
    ["copt_font_gamma"] = 56,
    ["copt_font_hinting"] = 2,
    ["copt_font_kerning"] = 3,
    ["copt_font_size"] = 29.5,
    ["copt_h_page_margins"] = {
        [1] = 15,
        [2] = 15,
    },
    ["copt_line_spacing"] = 130,
    ["copt_nightmode_images"] = 1,
    ["copt_render_dpi"] = 96,
    ["copt_rotation_mode"] = 0,
    ["copt_smooth_scaling"] = 0,
    ["copt_status_line"] = 1,
    ["copt_sync_t_b_page_margins"] = 1,
    ["copt_t_page_margin"] = 15,
    ["copt_view_mode"] = 0,
    ["copt_visible_pages"] = 1,
    ["copt_word_expansion"] = 0,
    ["copt_word_spacing"] = {
        [1] = 95,
        [2] = 75,
    },
    ["style_tweaks"] = {
        ["footnote-inpage_epub"] = true,
        ["footnote-inpage_fb2"] = true,
        ["inpage_footnote_font-size_smaller"] = true,
    },
    ["highlight_lighten_factor"] = 0.2,
    ["default_highlight_action"] = "ask",
    ["highlight_dialog_position"] = "center",
    ["back_in_reader"] = "previous_location",
    ["back_to_exit"] = "prompt",
    ["back_in_filemanager"] = "default",
    ["kopt_page_scroll"] = 0,
    ["kopt_trim_page"] = 3,
    ["kopt_zoom_mode_type"] = 2,
    ["panel_zoom_enabled"] = {
        ["cbt"] = true,
        ["cbz"] = true,
    },
    ["panel_zoom_fallback_to_text_selection"] = {
        ["pdf"] = true,
    },
    ["full_refresh_count"] = 30,
    ["night_full_refresh_count"] = 20,
    ["refresh_rate_2"] = 30,
    ["night_refresh_rate_2"] = 20,
    ["refresh_on_chapter_boundaries"] = true,
    ["no_refresh_on_second_chapter_page"] = true,
    ["refresh_on_pages_with_images"] = false,
    ["avoid_flashing_ui"] = true,
    ["flash_keyboard"] = true,
    ["page_turns_tap_zones"] = "left_right",
    ["page_turns_tap_zone_backward_size_ratio"] = 0.3,
    ["page_turns_tap_zone_forward_size_ratio"] = 0.3,
    ["low_pan_rate"] = true,
    ["inertial_scroll"] = false,
    ["multiswipes_enabled"] = false,
    ["ges_tap_interval_on_keyboard_ms"] = 0,
    ["scroll_method"] = "classic",
    ["auto_suspend_timeout_seconds"] = 900,
    ["autoshutdown_timeout_seconds"] = 259200,
    ["keepalive"] = true,
    ["auto_save_settings_interval_minutes"] = false,
    ["end_document_action"] = "mark_read",
    ["opening_page_location_stack"] = true,
    ["statistics"] = {
        ["calendar_browse_future_months"] = false,
        ["calendar_nb_book_spans"] = 3,
        ["calendar_show_histogram"] = true,
        ["calendar_start_day_of_week"] = 2,
        ["color"] = false,
        ["convert_to_db"] = true,
        ["freeze_finished_books"] = false,
        ["is_enabled"] = true,
        ["max_sec"] = 120,
        ["min_sec"] = 5,
    },
    ["device_status_battery_interval_minutes"] = 10,
    ["device_status_battery_threshold"] = 20,
    ["device_status_battery_threshold_high"] = 100,
    ["device_status_memory_interval_minutes"] = 5,
    ["device_status_memory_threshold"] = 100,
    ["dimension_units"] = "mm",
    ["duration_format"] = "classic",
    ["plugins_disabled"] = {
        ["SSH"] = true,
        ["archiveviewer"] = true,
        ["autodim"] = true,
        ["autoturn"] = true,
        ["autowarmth"] = true,
        ["bookshortcuts"] = true,
        ["cloudstorage"] = true,
        ["docsettingtweak"] = true,
        ["exporter"] = true,
        ["externalkeyboard"] = true,
        ["httpinspector"] = true,
        ["japanese"] = true,
        ["koaireader"] = true,
        ["kosync"] = true,
        ["movetoarchive"] = true,
        ["newsdownloader"] = true,
        ["opds"] = true,
        ["perceptionexpander"] = true,
        ["profiles"] = true,
        ["qrclipboard"] = true,
        ["readtimer"] = true,
        ["terminal"] = true,
        ["texteditor"] = true,
        ["timesync"] = true,
        ["vocabbuilder"] = true,
        ["wallabag"] = true,
    },
    ["quick_settings_panel"] = {
        ["button_order"] = {
            [1] = "wifi",
            [2] = "night",
            [3] = "rotate",
            [4] = "usb",
            [5] = "search",
            [6] = "quickrss",
            [7] = "cloud",
            [8] = "zlibrary",
            [9] = "calibre",
            [10] = "notion",
            [11] = "streak",
            [12] = "opds",
            [13] = "filebrowser",
            [14] = "restart",
            [15] = "exit",
            [16] = "sleep",
        },
        ["open_on_start"] = true,
        ["show_buttons"] = {
            ["calibre"] = false,
            ["cloud"] = false,
            ["exit"] = false,
            ["filebrowser"] = false,
            ["night"] = false,
            ["notion"] = false,
            ["opds"] = false,
            ["quickrss"] = false,
            ["restart"] = false,
            ["rotate"] = false,
            ["search"] = false,
            ["sleep"] = true,
            ["streak"] = false,
            ["usb"] = false,
            ["wifi"] = true,
            ["zlibrary"] = false,
        },
        ["show_frontlight"] = true,
        ["show_warmth"] = false,
    },
    ["cover_mode_drawers"] = {
        ["lighten"] = true,
    },
    ["cover_mode_enabled"] = true,
    ["cover_mode_toggle_mode"] = 1,
    ["coverbrowser_initial_default_setup_done"] = true,
    ["show_filter"] = {},
    ["show_flat_view"] = false,
    ["quickstart_shown_version"] = 202607020000,
    ["reading_insights_popup_mode"] = "days",
    ["book_receipt_bg_image_mode"] = "stretch",
    ["book_receipt_content_mode"] = "book_receipt",
    ["book_receipt_screensaver_background"] = "book_cover",
    ["wikipedia_disable_history"] = true,
    ["wikipedia_show_image"] = false,
    ["translator_from_doc_lang"] = true,
    ["text_lang_fallback"] = "en-US",
    -- filebrowserplus 无线访问（装机包补充：开机自启；密码由用户自行设置）
    ["FilebrowserPlus_autostart"] = true,
}
