-- ./settings.reader.lua
return {
    ["FilebrowserPlus_allow_no_password"] = true,
    ["FilebrowserPlus_auto_stop_minutes"] = 0,
    ["FilebrowserPlus_autostart"] = true,
    ["activate_menu"] = "swipe",
    ["activate_menu_top"] = "tap",
    ["auto_save_settings_interval_minutes"] = false,
    ["auto_standby_timeout_seconds"] = -1,
    ["auto_suspend_timeout_seconds"] = 1800,
    ["autodim_duration_seconds"] = 5,
    ["autodim_fraction"] = 20,
    ["autodim_starttime_minutes"] = 5,
    ["autoremove_deleted_items_from_history"] = true,
    ["autoshutdown_timeout_seconds"] = 259200,
    ["autoturn_distance"] = 1,
    ["autoturn_timeout_seconds"] = 0,
    ["autowarmth_fl_off_during_day_offset_s"] = 0,
    ["autowarmth_timezone"] = 0,
    ["avoid_flashing_ui"] = true,
    ["back_in_filemanager"] = "default",
    ["back_in_reader"] = "previous_location",
    ["back_to_exit"] = "prompt",
    ["book_map_ten_pages_markers"] = 0,
    ["book_receipt_bg_image_mode"] = "stretch",
    ["book_receipt_content_mode"] = "book_receipt",
    ["book_receipt_screensaver_background"] = "book_cover",
    ["bookmarks_items_per_page"] = 14,
    ["bookmarks_items_text_type"] = "note",
    ["clipboard"] = {},
    ["closed_rotation_mode"] = 0,
    ["collate"] = "access",
    ["companion_api_key"] = "",
    ["companion_provider"] = "deepseek",
    ["copt_b_page_margin"] = 15,
    ["copt_block_rendering_mode"] = 2,
    ["copt_cjk_width_scaling"] = 100,
    ["copt_css"] = "./data/epub.css",
    ["copt_embedded_css"] = 1,
    ["copt_embedded_fonts"] = 1,
    ["copt_font_base_weight"] = 1.5,
    ["copt_font_gamma"] = 56,
    ["copt_font_hinting"] = 2,
    ["copt_font_kerning"] = 3,
    ["copt_font_size"] = 29.5,
    ["copt_h_page_margins"] = {
        [1] = 15,
        [2] = 15,
    },
    ["copt_line_spacing"] = 130,
    ["copt_nightmode_images"] = 1,
    ["copt_render_dpi"] = 96,
    ["copt_rotation_mode"] = 0,
    ["copt_smooth_scaling"] = 0,
    ["copt_status_line"] = 1,
    ["copt_sync_t_b_page_margins"] = 1,
    ["copt_t_page_margin"] = 15,
    ["copt_view_mode"] = 0,
    ["copt_visible_pages"] = 1,
    ["copt_word_expansion"] = 0,
    ["copt_word_spacing"] = {
        [1] = 95,
        [2] = 75,
    },
    ["cover_mode_drawers"] = {
        ["lighten"] = true,
    },
    ["cover_mode_enabled"] = true,
    ["cover_mode_toggle_mode"] = 1,
    ["coverbrowser_initial_default_setup_done"] = true,
    ["cre_adjusted_fallback_font_sizes"] = false,
    ["cre_font"] = "TsangerXuanSan01JF",
    ["cre_font_family_fonts"] = {},
    ["cre_fonts_recently_selected"] = {
        [1] = "TsangerXuanSan01JF",
        [2] = "AaBTWLTCT (Non-Commercial Use)",
        [3] = "BJPJJP",
        [4] = "AXTRQLDY (Non-Commercial Use)",
        [5] = "AR SYSongGB Display H46",
        [6] = "Zilla Slab",
        [7] = "Poppins",
        [8] = "Pixelify Sans",
        [9] = "Literata",
        [10] = "Jost",
        [11] = "Google Sans",
        [12] = "Caveat",
        [13] = "Bangers",
        [14] = "Atkinson Hyperlegible Next",
        [15] = "Noto Serif",
        [16] = "Amazon Ember",
        [17] = "HYKongShanKai",
        [18] = "STYuanTC",
        [19] = "STKaitiTC",
        [20] = "STKaiti",
        [21] = "STZhongyuan",
        [22] = "STYuan",
        [23] = "Baskerville",
        [24] = "Bookerly",
        [25] = "Code2000",
        [26] = "Droid Sans Mono",
        [27] = "FreeSans",
        [28] = "FreeSerif",
        [29] = "Futura Medium",
        [30] = "Helvetica Neue LT 65 Kindle Medium",
        [31] = "Noto Naskh Arabic",
        [32] = "Noto Sans",
        [33] = "Noto Sans Arabic UI",
        [34] = "Noto Sans Bengali UI",
        [35] = "Noto Sans CJK SC",
        [36] = "Noto Sans Devanagari UI",
        [37] = "NotoSansKR",
        [38] = "NotoSerifKR",
        [39] = "OpenDyslexic",
        [40] = "PMN Caecilia LT",
        [41] = "Palatino",
        [42] = "STHeitiTC",
        [43] = "STSongTC",
    },
    ["cre_header_author"] = 0,
    ["cre_header_auto_refresh"] = 1,
    ["cre_header_battery"] = 1,
    ["cre_header_battery_percent"] = 0,
    ["cre_header_chapter_marks"] = 0,
    ["cre_header_clock"] = 1,
    ["cre_header_page_count"] = 1,
    ["cre_header_page_number"] = 1,
    ["cre_header_reading_percent"] = 0,
    ["cre_header_status_font_size"] = 20,
    ["cre_header_title"] = 0,
    ["default_highlight_action"] = "ask",
    ["dev_no_c_blitter"] = false,
    ["device_id"] = "AB59B52C303C42AD9BA12EE7786CDDDF",
    ["device_status_battery_interval_minutes"] = 10,
    ["device_status_battery_threshold"] = 20,
    ["device_status_battery_threshold_high"] = 100,
    ["device_status_memory_interval_minutes"] = 5,
    ["device_status_memory_threshold"] = 100,
    ["dict_button_config"] = {
        ["layout"] = {
            [1] = {
                [1] = "prev_dict",
                [2] = "highlight",
                [3] = "next_dict",
            },
            [2] = {
                [1] = "close",
            },
        },
        ["order"] = {
            [1] = "prev_dict",
            [2] = "highlight",
            [3] = "next_dict",
            [4] = "wikipedia",
            [5] = "search",
            [6] = "close",
            [7] = "translate",
        },
        ["row_count"] = {
            [1] = 3,
            [2] = 3,
        },
    },
    ["dict_font_size"] = 25,
    ["dict_largewindow"] = true,
    ["dict_presets"] = {
        ["严肃文学"] = {
            ["enabled_dict_names"] = {
                ["中华成语大词典 2.1"] = true,
                ["古汉语常用字字典"] = true,
                ["汉语大词典 离线版"] = true,
                ["现代汉语词典"] = true,
                ["诗词典故词典"] = true,
            },
        },
        ["中国哲学"] = {
            ["enabled_dict_names"] = {
                ["中华成语大词典 2.1"] = true,
                ["佛光大辞典"] = true,
                ["古汉语常用字字典"] = true,
                ["康熙字典文字版"] = true,
                ["汉语大词典 离线版"] = true,
                ["诗词典故词典"] = true,
            },
        },
        ["人文历史"] = {
            ["enabled_dict_names"] = {
                ["中华成语大词典 2.1"] = true,
                ["古汉语常用字字典"] = true,
                ["康熙字典文字版"] = true,
                ["汉语大词典 离线版"] = true,
                ["现代汉语词典"] = true,
                ["诗词典故词典"] = true,
            },
        },
        ["古典文学"] = {
            ["enabled_dict_names"] = {
                ["中华成语大词典 2.1"] = true,
                ["佛光大辞典"] = true,
                ["古汉语常用字字典"] = true,
                ["康熙字典文字版"] = true,
                ["汉语大词典 离线版"] = true,
                ["现代汉语词典"] = true,
                ["诗词典故词典"] = true,
            },
        },
        ["外国名著"] = {
            ["enabled_dict_names"] = {
                ["朗道汉英字典5.0"] = true,
                ["朗道英汉字典5.0"] = true,
                ["汉语大词典 离线版"] = true,
                ["牛津现代英汉双解词典"] = true,
                ["现代汉语词典"] = true,
            },
        },
        ["诗词格律"] = {
            ["enabled_dict_names"] = {
                ["中华成语大词典 2.1"] = true,
                ["古汉语常用字字典"] = true,
                ["康熙字典文字版"] = true,
                ["廣韻"] = true,
                ["廣韻反查"] = true,
                ["汉语大词典 离线版"] = true,
                ["诗词典故词典"] = true,
            },
        },
        ["通俗文学"] = {
            ["enabled_dict_names"] = {
                ["中华成语大词典 2.1"] = true,
                ["汉语大词典 离线版"] = true,
                ["现代汉语词典"] = true,
            },
        },
    },
    ["dicts_disabled"] = {
        ["data/dict/stardict-foguangdacidian-2.4.2/foguangdacidian.ifo"] = true,
        ["data/dict/stardict-guangyun-2.4.2/guangyun.ifo"] = true,
        ["data/dict/stardict-gyfancha-2.4.2/gyfancha.ifo"] = true,
    },
    ["dicts_order"] = {
        ["data/dict/stardict-chengyuda-2.4.2/chengyuda.ifo"] = 2,
        ["data/dict/stardict-chibigenc-2.4.2/chibigenc.ifo"] = 10,
        ["data/dict/stardict-foguangdacidian-2.4.2/foguangdacidian.ifo"] = 3,
        ["data/dict/stardict-ghycyzzd-2.4.2/ghycyzzd.ifo"] = 4,
        ["data/dict/stardict-guangyun-2.4.2/guangyun.ifo"] = 6,
        ["data/dict/stardict-gyfancha-2.4.2/gyfancha.ifo"] = 7,
        ["data/dict/stardict-kangxitext-2.4.2/kangxitext.ifo"] = 5,
        ["data/dict/stardict-langdao-ce-gb-2.4.2/langdao-ce-gb.ifo"] = 8,
        ["data/dict/stardict-langdao-ec-gb-2.4.2/langdao-ec-gb.ifo"] = 9,
        ["data/dict/stardict-oxford-gb-2.4.2/oxford-gb.ifo"] = 11,
        ["data/dict/stardict-poemstory-2.4.2/poemstory.ifo"] = 12,
        ["data/dict/stardict-xiandaihanyucidian_fix-2.4.2/xiandaihanyucidian_fix.ifo"] = 1,
    },
    ["dimension_units"] = "mm",
    ["document_metadata_folder"] = "doc",
    ["duration_format"] = "classic",
    ["end_document_action"] = "mark_read",
    ["exporter"] = {
        ["markdown"] = {
            ["formatting_options"] = {
                ["invert"] = "bold",
                ["lighten"] = "italic",
                ["strikeout"] = "strikethrough",
                ["underscore"] = "underline_markdownit",
            },
            ["highlight_formatting"] = true,
        },
    },
    ["fallback_font"] = "HYKongShanKai",
    ["filemanagermenu_tab_index"] = 1,
    ["flash_keyboard"] = true,
    ["folder_shortcuts"] = {
        ["/mnt/us/BOOKS"] = {
            ["providers"] = {
                ["home_dir"] = true,
            },
            ["time"] = 1787441815,
        },
    },
    ["folder_shortcuts_settings"] = {},
    ["font_menu_sort_by_recently_selected"] = true,
    ["footer"] = {
        ["align"] = "center",
        ["all_at_once"] = false,
        ["auto_refresh_time"] = false,
        ["battery"] = true,
        ["battery_hide_threshold"] = 100,
        ["book_author"] = false,
        ["book_author_max_width_pct"] = 30,
        ["book_chapter"] = false,
        ["book_chapter_max_width_pct"] = 30,
        ["book_time_to_read"] = false,
        ["book_title"] = false,
        ["book_title_max_width_pct"] = 30,
        ["bookmark_count"] = false,
        ["bottom_horizontal_separator"] = false,
        ["chapter_progress"] = false,
        ["chapter_progress_bar"] = false,
        ["chapter_time_to_read"] = false,
        ["container_bottom_padding"] = 1,
        ["container_height"] = 14,
        ["disable_progress_bar"] = true,
        ["disabled"] = false,
        ["frontlight"] = false,
        ["hide_empty_generators"] = false,
        ["initial_marker"] = false,
        ["invert_progress_direction"] = false,
        ["item_prefix"] = "icons",
        ["items_separator"] = "bar",
        ["lock_tap"] = false,
        ["mem_usage"] = false,
        ["page_progress"] = true,
        ["page_turning_inverted"] = false,
        ["pages_left"] = false,
        ["pages_left_book"] = false,
        ["pages_left_includes_current_page"] = false,
        ["percentage"] = false,
        ["progress_bar_min_width_pct"] = 20,
        ["progress_bar_position"] = "alongside",
        ["progress_margin"] = false,
        ["progress_margin_width"] = 10,
        ["progress_pct_format"] = "0",
        ["progress_style_thick_height"] = 7,
        ["progress_style_thin"] = false,
        ["progress_style_thin_height"] = 3,
        ["reclaim_height"] = false,
        ["skim_widget_on_hold"] = false,
        ["text_font_bold"] = false,
        ["text_font_face"] = "./fonts/noto/NotoSans-Regular.ttf",
        ["text_font_size"] = 14,
        ["time"] = true,
        ["toc_markers"] = true,
        ["toc_markers_width"] = 2,
        ["wifi_status"] = false,
    },
    ["footer_presets"] = {},
    ["full_refresh_count"] = 50,
    ["ges_tap_interval_on_keyboard_ms"] = 0,
    ["highlight_dialog_position"] = "center",
    ["highlight_lighten_factor"] = 0.2,
    ["history_filter"] = "all",
    ["history_freeze_finished_books"] = true,
    ["home_dir"] = "/mnt/us/BOOKS",
    ["httpinspector"] = {
        ["port"] = 8080,
    },
    ["hyph_user_dict"] = false,
    ["inbox_dir"] = "/mnt/us/BOOKS",
    ["inertial_scroll"] = false,
    ["inkstain_wallpaper"] = {},
    ["keepalive"] = false,
    ["keyboard_chinese_pinyin_settings"] = {
        ["show_candi"] = true,
    },
    ["keyboard_key_font_size"] = 22,
    ["keyboard_layout"] = "zh_CN",
    ["keyboard_layouts"] = {
        [1] = "zh_CN",
    },
    ["kopt_page_scroll"] = 0,
    ["kopt_trim_page"] = 3,
    ["kopt_zoom_mode_type"] = 2,
    ["language"] = "zh_CN",
    ["last_migration_date"] = 20260623,
    ["lastdir"] = "/mnt/us/BOOKS",
    ["lastfile"] = "/mnt/us/BOOKS/我的前半生 [纯净版].epub",
    ["lock_home_folder"] = false,
    ["low_pan_rate"] = true,
    ["menu_search_string"] = "我试试",
    ["multiswipes_enabled"] = false,
    ["night_full_refresh_count"] = 35,
    ["night_mode"] = false,
    ["night_refresh_rate_2"] = 35,
    ["no_refresh_on_second_chapter_page"] = true,
    ["notification_sources_to_show_mask"] = 0,
    ["opening_page_location_stack"] = true,
    ["ota_server"] = "http://ota.koreader.rocks/",
    ["page_turns_tap_zone_backward_size_ratio"] = 0.3,
    ["page_turns_tap_zone_forward_size_ratio"] = 0.3,
    ["page_turns_tap_zones"] = "left_right",
    ["panel_zoom_enabled"] = {
        ["cbt"] = true,
        ["cbz"] = true,
    },
    ["panel_zoom_fallback_to_text_selection"] = {
        ["pdf"] = true,
    },
    ["pinyin_arrow_select"] = true,
    ["pinyin_enabled"] = true,
    ["pinyin_enhancement_enabled"] = true,
    ["pinyin_font"] = "cfont",
    ["pinyin_font_size"] = 15,
    ["pinyin_level"] = 2,
    ["pinyin_phrase"] = false,
    ["pinyin_selection_history"] = {
        ["一"] = 1,
        ["一人"] = 2,
        ["三"] = 2,
        ["下"] = 3,
        ["不能"] = 1,
        ["不该"] = 1,
        ["严肃"] = 1,
        ["中国"] = 2,
        ["之"] = 2,
        ["书"] = 1,
        ["二"] = 15,
        ["人"] = 1,
        ["人文"] = 1,
        ["仇"] = 1,
        ["全"] = 1,
        ["六"] = 2,
        ["出"] = 1,
        ["剑"] = 1,
        ["历史"] = 1,
        ["古典"] = 1,
        ["名著"] = 1,
        ["名言"] = 1,
        ["哲学"] = 1,
        ["在"] = 1,
        ["坛"] = 2,
        ["壁纸"] = 2,
        ["外"] = 1,
        ["外国"] = 1,
        ["好"] = 1,
        ["安"] = 1,
        ["客"] = 2,
        ["宴席"] = 1,
        ["寡人"] = 1,
        ["小说"] = 1,
        ["少年"] = 1,
        ["局"] = 1,
        ["帝国"] = 2,
        ["常用"] = 1,
        ["广"] = 1,
        ["录"] = 1,
        ["彷徨"] = 1,
        ["律"] = 1,
        ["德"] = 1,
        ["恩"] = 1,
        ["我"] = 1,
        ["挂"] = 1,
        ["文"] = 3,
        ["文学"] = 3,
        ["文言文"] = 1,
        ["无"] = 1,
        ["时"] = 1,
        ["服装"] = 1,
        ["林"] = 1,
        ["格"] = 1,
        ["棋"] = 15,
        ["每日"] = 1,
        ["汉语"] = 1,
        ["沈"] = 1,
        ["法"] = 1,
        ["浪"] = 2,
        ["版"] = 2,
        ["猎"] = 1,
        ["现代"] = 1,
        ["白"] = 1,
        ["白话"] = 1,
        ["的"] = 1,
        ["皇帝"] = 1,
        ["祖"] = 2,
        ["空"] = 1,
        ["穿"] = 2,
        ["笑"] = 1,
        ["第"] = 2,
        ["简约"] = 1,
        ["米"] = 16,
        ["米尔"] = 1,
        ["经"] = 2,
        ["而"] = 1,
        ["行"] = 2,
        ["装"] = 1,
        ["西洋"] = 1,
        ["覆盖"] = 1,
        ["觅"] = 1,
        ["言"] = 2,
        ["记"] = 1,
        ["词典"] = 2,
        ["试"] = 3,
        ["诗词"] = 1,
        ["话"] = 1,
        ["语言"] = 1,
        ["货"] = 1,
        ["轻"] = 1,
        ["输入"] = 1,
        ["还是"] = 1,
        ["通俗"] = 2,
        ["醉"] = 1,
        ["量"] = 1,
        ["问"] = 1,
        ["问题"] = 1,
        ["阅"] = 1,
        ["魂"] = 13,
    },
    ["pinyin_traditional"] = false,
    ["pinyin_vocab_link"] = true,
    ["plugins_disabled"] = {
        ["SSH"] = true,
        ["archiveviewer"] = true,
        ["autodim"] = true,
        ["autoturn"] = true,
        ["autowarmth"] = true,
        ["bookshortcuts"] = true,
        ["cloudstorage"] = true,
        ["docsettingtweak"] = true,
        ["exporter"] = true,
        ["externalkeyboard"] = true,
        ["httpinspector"] = true,
        ["japanese"] = true,
        ["koaireader"] = true,
        ["kosync"] = true,
        ["movetoarchive"] = true,
        ["newsdownloader"] = true,
        ["opds"] = true,
        ["perceptionexpander"] = true,
        ["profiles"] = true,
        ["qrclipboard"] = true,
        ["readtimer"] = true,
        ["terminal"] = true,
        ["texteditor"] = true,
        ["timesync"] = true,
        ["wallabag"] = true,
    },
    ["profiles_autoexec"] = {},
    ["provider"] = {},
    ["quick_settings_panel"] = {
        ["button_order"] = {
            [1] = "wifi",
            [2] = "night",
            [3] = "rotate",
            [4] = "usb",
            [5] = "search",
            [6] = "quickrss",
            [7] = "cloud",
            [8] = "zlibrary",
            [9] = "calibre",
            [10] = "notion",
            [11] = "streak",
            [12] = "opds",
            [13] = "filebrowser",
            [14] = "restart",
            [15] = "exit",
            [16] = "sleep",
        },
        ["open_on_start"] = true,
        ["show_buttons"] = {
            ["calibre"] = false,
            ["cloud"] = false,
            ["exit"] = false,
            ["filebrowser"] = false,
            ["night"] = true,
            ["notion"] = false,
            ["opds"] = false,
            ["quickrss"] = false,
            ["restart"] = false,
            ["rotate"] = false,
            ["search"] = false,
            ["sleep"] = true,
            ["streak"] = false,
            ["usb"] = false,
            ["wifi"] = true,
            ["zlibrary"] = false,
        },
        ["show_frontlight"] = true,
        ["show_warmth"] = false,
    },
    ["quickstart_shown_version"] = 202607020000,
    ["reader_footer_custom_text"] = "KOReader",
    ["reader_footer_custom_text_repetitions"] = "1",
    ["reader_footer_mode"] = 1,
    ["readingInsights_cache"] = {
        ["monthlyReadingDays"] = {
            [2026] = {
                [1] = {
                    ["days"] = 0,
                    ["label"] = "1月",
                    ["label_full"] = "一月",
                    ["month"] = "2026-01",
                    ["month_num"] = 1,
                },
                [2] = {
                    ["days"] = 0,
                    ["label"] = "2月",
                    ["label_full"] = "二月",
                    ["month"] = "2026-02",
                    ["month_num"] = 2,
                },
                [3] = {
                    ["days"] = 0,
                    ["label"] = "3月",
                    ["label_full"] = "三月",
                    ["month"] = "2026-03",
                    ["month_num"] = 3,
                },
                [4] = {
                    ["days"] = 0,
                    ["label"] = "4月",
                    ["label_full"] = "四月",
                    ["month"] = "2026-04",
                    ["month_num"] = 4,
                },
                [5] = {
                    ["days"] = 0,
                    ["label"] = "5月",
                    ["label_full"] = "5月",
                    ["month"] = "2026-05",
                    ["month_num"] = 5,
                },
                [6] = {
                    ["days"] = 1,
                    ["label"] = "6月",
                    ["label_full"] = "六月",
                    ["month"] = "2026-06",
                    ["month_num"] = 6,
                },
                [7] = {
                    ["days"] = 0,
                    ["label"] = "7月",
                    ["label_full"] = "七月",
                    ["month"] = "2026-07",
                    ["month_num"] = 7,
                },
                [8] = {
                    ["days"] = 11,
                    ["label"] = "8月",
                    ["label_full"] = "八月",
                    ["month"] = "2026-08",
                    ["month_num"] = 8,
                },
                [9] = {
                    ["days"] = 0,
                    ["label"] = "9月",
                    ["label_full"] = "九月",
                    ["month"] = "2026-09",
                    ["month_num"] = 9,
                },
                [10] = {
                    ["days"] = 0,
                    ["label"] = "10月",
                    ["label_full"] = "十月",
                    ["month"] = "2026-10",
                    ["month_num"] = 10,
                },
                [11] = {
                    ["days"] = 0,
                    ["label"] = "11月",
                    ["label_full"] = "十一月",
                    ["month"] = "2026-11",
                    ["month_num"] = 11,
                },
                [12] = {
                    ["days"] = 0,
                    ["label"] = "12月",
                    ["label_full"] = "十二月",
                    ["month"] = "2026-12",
                    ["month_num"] = 12,
                },
            },
        },
        ["monthlyReadingHours"] = {
            [2026] = {
                [1] = {
                    ["hours"] = 0,
                    ["label"] = "1月",
                    ["label_full"] = "一月",
                    ["month"] = "2026-01",
                    ["month_num"] = 1,
                },
                [2] = {
                    ["hours"] = 0,
                    ["label"] = "2月",
                    ["label_full"] = "二月",
                    ["month"] = "2026-02",
                    ["month_num"] = 2,
                },
                [3] = {
                    ["hours"] = 0,
                    ["label"] = "3月",
                    ["label_full"] = "三月",
                    ["month"] = "2026-03",
                    ["month_num"] = 3,
                },
                [4] = {
                    ["hours"] = 0,
                    ["label"] = "4月",
                    ["label_full"] = "四月",
                    ["month"] = "2026-04",
                    ["month_num"] = 4,
                },
                [5] = {
                    ["hours"] = 0,
                    ["label"] = "5月",
                    ["label_full"] = "5月",
                    ["month"] = "2026-05",
                    ["month_num"] = 5,
                },
                [6] = {
                    ["hours"] = 0.1,
                    ["label"] = "6月",
                    ["label_full"] = "六月",
                    ["month"] = "2026-06",
                    ["month_num"] = 6,
                },
                [7] = {
                    ["hours"] = 0,
                    ["label"] = "7月",
                    ["label_full"] = "七月",
                    ["month"] = "2026-07",
                    ["month_num"] = 7,
                },
                [8] = {
                    ["hours"] = 11,
                    ["label"] = "8月",
                    ["label_full"] = "八月",
                    ["month"] = "2026-08",
                    ["month_num"] = 8,
                },
                [9] = {
                    ["hours"] = 0,
                    ["label"] = "9月",
                    ["label_full"] = "九月",
                    ["month"] = "2026-09",
                    ["month_num"] = 9,
                },
                [10] = {
                    ["hours"] = 0,
                    ["label"] = "10月",
                    ["label_full"] = "十月",
                    ["month"] = "2026-10",
                    ["month_num"] = 10,
                },
                [11] = {
                    ["hours"] = 0,
                    ["label"] = "11月",
                    ["label_full"] = "十一月",
                    ["month"] = "2026-11",
                    ["month_num"] = 11,
                },
                [12] = {
                    ["hours"] = 0,
                    ["label"] = "12月",
                    ["label_full"] = "十二月",
                    ["month"] = "2026-12",
                    ["month_num"] = 12,
                },
            },
        },
        ["streaks"] = {
            ["days"] = {
                ["best"] = 11,
                ["best_end"] = 1787675100,
                ["best_start"] = 1786825075,
                ["current"] = 11,
            },
            ["weeks"] = {
                ["best"] = 3,
                ["best_end"] = 1787684098,
                ["best_start"] = 1786825075,
                ["current"] = 3,
            },
        },
        ["yearRange"] = {
            ["max_year"] = 2026,
            ["min_year"] = 2026,
        },
        ["yearlyStats"] = {
            [2026] = {
                ["days"] = 12,
                ["duration"] = 40582,
                ["pages"] = 601,
            },
        },
    },
    ["readingInsights_cacheTimestamps"] = {
        ["fullClear"] = 0,
        ["lastRefreshed"] = 1787684559,
        ["partialClear"] = 1787684556,
        ["statsSynced"] = 0,
    },
    ["reading_insights_popup_mode"] = "days",
    ["readtimer"] = {},
    ["refresh_on_chapter_boundaries"] = true,
    ["refresh_on_pages_with_images"] = false,
    ["refresh_rate_2"] = 50,
    ["screensaver_delay"] = "disable",
    ["screensaver_extra_flash_count"] = 0,
    ["screensaver_extra_flash_delay"] = 1000,
    ["screensaver_hide_fallback_msg"] = false,
    ["screensaver_img_background"] = "none",
    ["screensaver_message_alpha"] = 100,
    ["screensaver_message_container"] = "box",
    ["screensaver_message_vertical_position"] = 50,
    ["screensaver_msg_background"] = "none",
    ["screensaver_rotate_auto_for_best_fit"] = false,
    ["screensaver_show_message"] = false,
    ["screensaver_stretch_images"] = true,
    ["screensaver_type"] = "customisable_ss",
    ["scroll_method"] = "classic",
    ["show_bottom_menu"] = false,
    ["show_filter"] = {},
    ["show_flat_view"] = false,
    ["simplebookshelf_return_page"] = 1,
    ["simplebookshelf_return_pending"] = true,
    ["simpleui_book_origin"] = "simplebookshelf",
    ["simpleui_userdata_migrated_v1"] = true,
    ["start_with"] = "homescreen_simpleui",
    ["statistics"] = {
        ["calendar_browse_future_months"] = false,
        ["calendar_nb_book_spans"] = 3,
        ["calendar_show_histogram"] = true,
        ["calendar_start_day_of_week"] = 2,
        ["color"] = false,
        ["convert_to_db"] = true,
        ["freeze_finished_books"] = false,
        ["is_enabled"] = true,
        ["max_sec"] = 120,
        ["min_sec"] = 5,
    },
    ["style_tweaks"] = {
        ["footnote-inpage_epub"] = true,
        ["footnote-inpage_fb2"] = true,
        ["inpage_footnote_font-size_smaller"] = true,
    },
    ["style_tweaks_in_dispatcher"] = {},
    ["sui_upd_dl_url"] = "https://github.com/doctorhetfield-cmd/simpleui.koplugin/releases/download/2.5.0/simpleui.koplugin.zip",
    ["sui_upd_has_update"] = false,
    ["sui_upd_last_check"] = 1787082623,
    ["sui_upd_latest_ver"] = "2.5.0",
    ["swipe_animation_delay_ms_horizontal"] = 13,
    ["swipe_animation_delay_ms_vertical"] = 13,
    ["swipe_animation_mild_global_refresh"] = true,
    ["swipe_animations"] = true,
    ["terminal_buffer_size"] = 16,
    ["terminal_shell"] = "/bin/ash",
    ["text_lang_fallback"] = "en-US",
    ["toc_items_per_page"] = 14,
    ["translator_from_doc_lang"] = true,
    ["ui_font_name"] = "HYKongShanKai",
    ["visual_overhaul_cover"] = {
        ["ar_den"] = 3,
        ["ar_num"] = 2,
        ["border_width"] = 1.5,
        ["card_gap"] = 3,
        ["corner_radius"] = 0,
        ["dogear_size"] = 0,
        ["file_count_size"] = 15,
        ["fill"] = false,
        ["folder_font_size"] = 25,
        ["hide_title_meta"] = true,
        ["meta_font_size"] = 8,
        ["new_badge_days"] = 9000,
        ["new_badge_inset_x"] = -25,
        ["new_badge_inset_y"] = -8,
        ["new_badge_size"] = 75,
        ["pages_badge_size"] = 10,
        ["pages_border_w"] = 2,
        ["pages_corner"] = 10,
        ["pages_enabled"] = false,
        ["pages_font_size"] = 0.5,
        ["pct_badge_size"] = 55,
        ["pct_move_x"] = 3,
        ["pct_move_y"] = -1,
        ["pct_text_size"] = 0.3,
        ["stretch_limit"] = 50,
        ["title_font_size"] = 10,
        ["title_max_lines"] = 1,
        ["title_padding"] = 3,
        ["top_margin"] = 0,
    },
    ["vocabulary_builder"] = {
        ["enabled"] = false,
        ["with_context"] = true,
    },
    ["wifi_was_on"] = true,
    ["wikipedia_disable_history"] = true,
    ["wikipedia_show_image"] = false,
}
