-- ./settings/simpleui/sui_settings.lua
return {
    ["simpleui_bar_enabled"] = true,
    ["simpleui_bar_mode"] = "icons",
    ["simpleui_bar_rs_text_scale_pct"] = 160,
    ["simpleui_bar_size_pct"] = 70,
    ["simpleui_bar_style"] = "bare",
    ["simpleui_bar_tabs"] = {
        [1] = "wifi_toggle",
        [2] = "homescreen",
        [3] = "continue",
        [4] = "home",
        [5] = "power",
    },
    ["simpleui_browsemeta_enabled"] = true,
    ["simpleui_browsemeta_mode"] = "series",
    ["simpleui_cqa_list"] = {},
    ["simpleui_cqa_migrated_v1"] = true,
    ["simpleui_daily_reading_goal_secs"] = 1800,
    ["simpleui_defaults_v1"] = true,
    ["simpleui_defaults_v2"] = true,
    ["simpleui_defaults_v3"] = true,
    ["simpleui_enabled"] = true,
    ["simpleui_fc_cover_mode"] = "default",
    ["simpleui_fc_enabled"] = true,
    ["simpleui_fc_folder_style"] = "auto",
    ["simpleui_fc_recursive_cover"] = false,
    ["simpleui_fc_series_grouping"] = false,
    ["simpleui_fc_show_author_strip"] = true,
    ["simpleui_fc_show_title_strip"] = true,
    ["simpleui_fc_subfolder_cover"] = false,
    ["simpleui_hide_label_clock"] = false,
    ["simpleui_hide_label_coverdeck"] = false,
    ["simpleui_hide_label_currently"] = false,
    ["simpleui_hide_label_reading_goals"] = true,
    ["simpleui_hide_label_recent"] = false,
    ["simpleui_home_key_opens_hs"] = true,
    ["simpleui_hs_action_list_enabled"] = false,
    ["simpleui_hs_active_preset"] = "壁纸版-轻量简约",
    ["simpleui_hs_clock_battery"] = false,
    ["simpleui_hs_clock_date"] = false,
    ["simpleui_hs_clock_enabled"] = false,
    ["simpleui_hs_clock_scale"] = 110,
    ["simpleui_hs_collections"] = false,
    ["simpleui_hs_collections_enabled"] = false,
    ["simpleui_hs_coverdeck"] = false,
    ["simpleui_hs_coverdeck_enabled"] = true,
    ["simpleui_hs_coverdeck_gap_pct"] = 0,
    ["simpleui_hs_coverdeck_item_label_scale"] = 100,
    ["simpleui_hs_coverdeck_main_order"] = {
        [1] = "covers",
        [2] = "title",
        [3] = "author",
        [4] = "progress",
        [5] = "stats",
    },
    ["simpleui_hs_coverdeck_scale"] = 80,
    ["simpleui_hs_coverdeck_show_author"] = false,
    ["simpleui_hs_coverdeck_show_book_days"] = false,
    ["simpleui_hs_coverdeck_show_book_remaining"] = false,
    ["simpleui_hs_coverdeck_show_book_time"] = false,
    ["simpleui_hs_coverdeck_show_finished"] = true,
    ["simpleui_hs_coverdeck_show_percent"] = true,
    ["simpleui_hs_coverdeck_show_progress"] = true,
    ["simpleui_hs_coverdeck_show_stats"] = false,
    ["simpleui_hs_coverdeck_show_title"] = false,
    ["simpleui_hs_coverdeck_source"] = "tbr",
    ["simpleui_hs_coverdeck_stats_order"] = {},
    ["simpleui_hs_coverdeck_thumb_scale"] = 160,
    ["simpleui_hs_coverdeck_title_pos"] = "below",
    ["simpleui_hs_currently"] = true,
    ["simpleui_hs_currently_bar_style"] = "with_pct",
    ["simpleui_hs_currently_elem_order"] = {
        [1] = "title",
        [2] = "author",
        [3] = "progress",
        [4] = "percent",
    },
    ["simpleui_hs_currently_enabled"] = false,
    ["simpleui_hs_currently_show_author"] = true,
    ["simpleui_hs_currently_show_book_days"] = false,
    ["simpleui_hs_currently_show_book_remaining"] = false,
    ["simpleui_hs_currently_show_book_time"] = false,
    ["simpleui_hs_currently_show_description"] = true,
    ["simpleui_hs_currently_show_frame"] = false,
    ["simpleui_hs_currently_show_percent"] = true,
    ["simpleui_hs_currently_show_progress"] = true,
    ["simpleui_hs_currently_show_series"] = false,
    ["simpleui_hs_currently_show_title"] = true,
    ["simpleui_hs_currently_solid_bg"] = false,
    ["simpleui_hs_currently_stats_style"] = "default",
    ["simpleui_hs_flat_library_enabled"] = false,
    ["simpleui_hs_header"] = "clock_date",
    ["simpleui_hs_header_enabled"] = true,
    ["simpleui_hs_heatmap_enabled"] = false,
    ["simpleui_hs_module_order"] = {
        [1] = "coverdeck",
        [2] = "reading_stats",
        [3] = "clock",
        [4] = "quote",
        [5] = "currently",
        [6] = "recent",
        [7] = "new_books",
        [8] = "tbr",
        [9] = "collections",
        [10] = "flat_library",
        [11] = "reading_goals",
        [12] = "heatmap",
        [13] = "action_list",
    },
    ["simpleui_hs_new_books_enabled"] = false,
    ["simpleui_hs_presets"] = {
        ["壁纸版-轻量简约"] = {
            ["simpleui_hs_action_list_enabled"] = false,
            ["simpleui_hs_clock_battery"] = false,
            ["simpleui_hs_clock_date"] = false,
            ["simpleui_hs_clock_enabled"] = false,
            ["simpleui_hs_clock_scale"] = 110,
            ["simpleui_hs_collections"] = false,
            ["simpleui_hs_collections_enabled"] = false,
            ["simpleui_hs_coverdeck"] = false,
            ["simpleui_hs_coverdeck_enabled"] = true,
            ["simpleui_hs_coverdeck_item_label_scale"] = 100,
            ["simpleui_hs_coverdeck_main_order"] = {
                [1] = "covers",
                [2] = "title",
                [3] = "author",
                [4] = "progress",
                [5] = "stats",
            },
            ["simpleui_hs_coverdeck_scale"] = 100,
            ["simpleui_hs_coverdeck_show_author"] = false,
            ["simpleui_hs_coverdeck_show_book_days"] = false,
            ["simpleui_hs_coverdeck_show_book_remaining"] = false,
            ["simpleui_hs_coverdeck_show_book_time"] = false,
            ["simpleui_hs_coverdeck_show_finished"] = true,
            ["simpleui_hs_coverdeck_show_percent"] = true,
            ["simpleui_hs_coverdeck_show_progress"] = true,
            ["simpleui_hs_coverdeck_show_stats"] = false,
            ["simpleui_hs_coverdeck_show_title"] = false,
            ["simpleui_hs_coverdeck_source"] = "tbr",
            ["simpleui_hs_coverdeck_stats_order"] = {},
            ["simpleui_hs_coverdeck_thumb_scale"] = 110,
            ["simpleui_hs_coverdeck_title_pos"] = "below",
            ["simpleui_hs_currently"] = true,
            ["simpleui_hs_currently_bar_style"] = "with_pct",
            ["simpleui_hs_currently_elem_order"] = {
                [1] = "title",
                [2] = "author",
                [3] = "progress",
                [4] = "percent",
            },
            ["simpleui_hs_currently_enabled"] = false,
            ["simpleui_hs_currently_show_author"] = true,
            ["simpleui_hs_currently_show_book_days"] = false,
            ["simpleui_hs_currently_show_book_remaining"] = false,
            ["simpleui_hs_currently_show_book_time"] = false,
            ["simpleui_hs_currently_show_description"] = true,
            ["simpleui_hs_currently_show_frame"] = false,
            ["simpleui_hs_currently_show_percent"] = true,
            ["simpleui_hs_currently_show_progress"] = true,
            ["simpleui_hs_currently_show_series"] = false,
            ["simpleui_hs_currently_show_title"] = true,
            ["simpleui_hs_currently_solid_bg"] = false,
            ["simpleui_hs_currently_stats_style"] = "default",
            ["simpleui_hs_flat_library_enabled"] = false,
            ["simpleui_hs_header"] = "clock_date",
            ["simpleui_hs_header_enabled"] = true,
            ["simpleui_hs_module_order"] = {
                [1] = "coverdeck",
                [2] = "reading_stats",
                [3] = "clock",
                [4] = "quote",
                [5] = "currently",
                [6] = "recent",
                [7] = "new_books",
                [8] = "tbr",
                [9] = "collections",
                [10] = "reading_goals",
                [11] = "action_list",
            },
            ["simpleui_hs_new_books_enabled"] = false,
            ["simpleui_hs_quick_actions_1_enabled"] = false,
            ["simpleui_hs_quick_actions_1_items"] = {
                [1] = "bookmark_browser",
            },
            ["simpleui_hs_quick_actions_2_enabled"] = false,
            ["simpleui_hs_quick_actions_3_enabled"] = false,
            ["simpleui_hs_quote_align"] = "center",
            ["simpleui_hs_quote_enabled"] = false,
            ["simpleui_hs_quote_scale"] = 100,
            ["simpleui_hs_quote_source"] = "quotes",
            ["simpleui_hs_reading_goals"] = false,
            ["simpleui_hs_reading_goals_elem_order"] = {
                [1] = "annual",
                [2] = "monthly",
                [3] = "daily",
            },
            ["simpleui_hs_reading_goals_enabled"] = false,
            ["simpleui_hs_reading_goals_scale"] = 90,
            ["simpleui_hs_reading_goals_show_frame"] = false,
            ["simpleui_hs_reading_goals_solid_bg"] = false,
            ["simpleui_hs_reading_stats_enabled"] = true,
            ["simpleui_hs_reading_stats_items"] = {
                [1] = "today_time",
                [2] = "today_pages",
                [3] = "total_time",
            },
            ["simpleui_hs_reading_stats_scale"] = 80,
            ["simpleui_hs_reading_stats_type"] = "list",
            ["simpleui_hs_recent"] = true,
            ["simpleui_hs_recent_enabled"] = false,
            ["simpleui_hs_recent_progress_style"] = "bar_text",
            ["simpleui_hs_recent_show_finished"] = true,
            ["simpleui_hs_recent_show_frame"] = true,
            ["simpleui_hs_recent_show_overlay"] = false,
            ["simpleui_hs_recent_show_progress"] = true,
            ["simpleui_hs_recent_show_text"] = true,
            ["simpleui_hs_recent_solid_bg"] = false,
            ["simpleui_hs_return_on_wakeup"] = true,
            ["simpleui_hs_simpleui_quote_align"] = "center",
            ["simpleui_hs_simpleui_quote_fixed_height"] = true,
            ["simpleui_hs_simpleui_quote_source"] = "highlights",
            ["simpleui_hs_tbr_enabled"] = false,
            ["simpleui_layout"] = {
                ["pages"] = {
                    [1] = {
                        ["id"] = 1,
                        ["modules"] = {
                            [1] = "coverdeck",
                            [2] = "reading_stats",
                        },
                    },
                },
            },
            ["simpleui_navbar_transparent"] = false,
            ["simpleui_qa_row_instances"] = {},
            ["simpleui_reading_goals_layout"] = "compact",
            ["simpleui_reading_goals_show_annual"] = false,
            ["simpleui_reading_goals_show_daily"] = true,
            ["simpleui_reading_goals_show_monthly"] = false,
            ["simpleui_statusbar_transparent"] = false,
            ["simpleui_style_progress_bar_type"] = "flat",
            ["simpleui_style_wallpaper"] = "./settings/simpleui/sui_wallpapers/wallpaper1.png",
            ["simpleui_style_wallpaper_enabled"] = true,
            ["simpleui_style_wallpaper_opacity"] = 0,
            ["simpleui_wallpaper_show_in_fm"] = false,
        },
        ["无壁纸-每日名言版"] = {
            ["simpleui_hs_action_list_enabled"] = false,
            ["simpleui_hs_clock_battery"] = false,
            ["simpleui_hs_clock_date"] = true,
            ["simpleui_hs_clock_enabled"] = false,
            ["simpleui_hs_clock_scale"] = 110,
            ["simpleui_hs_collections"] = false,
            ["simpleui_hs_collections_enabled"] = false,
            ["simpleui_hs_coverdeck"] = false,
            ["simpleui_hs_coverdeck_enabled"] = true,
            ["simpleui_hs_coverdeck_item_label_scale"] = 100,
            ["simpleui_hs_coverdeck_main_order"] = {
                [1] = "covers",
                [2] = "title",
                [3] = "author",
                [4] = "progress",
                [5] = "stats",
            },
            ["simpleui_hs_coverdeck_show_author"] = false,
            ["simpleui_hs_coverdeck_show_book_days"] = false,
            ["simpleui_hs_coverdeck_show_book_remaining"] = false,
            ["simpleui_hs_coverdeck_show_book_time"] = false,
            ["simpleui_hs_coverdeck_show_finished"] = true,
            ["simpleui_hs_coverdeck_show_percent"] = true,
            ["simpleui_hs_coverdeck_show_progress"] = true,
            ["simpleui_hs_coverdeck_show_stats"] = false,
            ["simpleui_hs_coverdeck_show_title"] = true,
            ["simpleui_hs_coverdeck_source"] = "tbr",
            ["simpleui_hs_coverdeck_stats_order"] = {},
            ["simpleui_hs_coverdeck_thumb_scale"] = 100,
            ["simpleui_hs_coverdeck_title_pos"] = "below",
            ["simpleui_hs_currently"] = true,
            ["simpleui_hs_currently_bar_style"] = "with_pct",
            ["simpleui_hs_currently_elem_order"] = {
                [1] = "title",
                [2] = "author",
                [3] = "progress",
                [4] = "percent",
            },
            ["simpleui_hs_currently_enabled"] = false,
            ["simpleui_hs_currently_show_author"] = true,
            ["simpleui_hs_currently_show_book_days"] = false,
            ["simpleui_hs_currently_show_book_remaining"] = false,
            ["simpleui_hs_currently_show_book_time"] = false,
            ["simpleui_hs_currently_show_description"] = true,
            ["simpleui_hs_currently_show_frame"] = false,
            ["simpleui_hs_currently_show_percent"] = true,
            ["simpleui_hs_currently_show_progress"] = true,
            ["simpleui_hs_currently_show_series"] = false,
            ["simpleui_hs_currently_show_title"] = true,
            ["simpleui_hs_currently_solid_bg"] = false,
            ["simpleui_hs_currently_stats_style"] = "default",
            ["simpleui_hs_flat_library_enabled"] = false,
            ["simpleui_hs_header"] = "clock_date",
            ["simpleui_hs_header_enabled"] = true,
            ["simpleui_hs_module_order"] = {
                [1] = "clock",
                [2] = "coverdeck",
                [3] = "quote",
                [4] = "reading_goals",
                [5] = "reading_stats",
                [6] = "currently",
                [7] = "recent",
                [8] = "new_books",
                [9] = "tbr",
                [10] = "collections",
                [11] = "action_list",
            },
            ["simpleui_hs_new_books_enabled"] = false,
            ["simpleui_hs_quick_actions_1_enabled"] = false,
            ["simpleui_hs_quick_actions_1_items"] = {
                [1] = "bookmark_browser",
            },
            ["simpleui_hs_quick_actions_2_enabled"] = false,
            ["simpleui_hs_quick_actions_3_enabled"] = false,
            ["simpleui_hs_quote_align"] = "center",
            ["simpleui_hs_quote_enabled"] = true,
            ["simpleui_hs_quote_scale"] = 100,
            ["simpleui_hs_quote_source"] = "quotes",
            ["simpleui_hs_reading_goals"] = false,
            ["simpleui_hs_reading_goals_elem_order"] = {
                [1] = "annual",
                [2] = "monthly",
                [3] = "daily",
            },
            ["simpleui_hs_reading_goals_enabled"] = true,
            ["simpleui_hs_reading_goals_scale"] = 90,
            ["simpleui_hs_reading_goals_show_frame"] = false,
            ["simpleui_hs_reading_goals_solid_bg"] = false,
            ["simpleui_hs_reading_stats_enabled"] = true,
            ["simpleui_hs_reading_stats_items"] = {
                [1] = "streak",
                [2] = "today_pages",
                [3] = "avg_time",
                [4] = "total_time",
                [5] = "total_books",
            },
            ["simpleui_hs_reading_stats_scale"] = 80,
            ["simpleui_hs_reading_stats_type"] = "cards",
            ["simpleui_hs_recent"] = true,
            ["simpleui_hs_recent_enabled"] = false,
            ["simpleui_hs_recent_progress_style"] = "bar_text",
            ["simpleui_hs_recent_show_finished"] = true,
            ["simpleui_hs_recent_show_frame"] = true,
            ["simpleui_hs_recent_show_overlay"] = false,
            ["simpleui_hs_recent_show_progress"] = true,
            ["simpleui_hs_recent_show_text"] = true,
            ["simpleui_hs_recent_solid_bg"] = false,
            ["simpleui_hs_return_on_wakeup"] = true,
            ["simpleui_hs_simpleui_quote_align"] = "center",
            ["simpleui_hs_simpleui_quote_fixed_height"] = true,
            ["simpleui_hs_simpleui_quote_source"] = "highlights",
            ["simpleui_hs_tbr_enabled"] = false,
            ["simpleui_layout"] = {
                ["pages"] = {
                    [1] = {
                        ["id"] = 1,
                        ["modules"] = {
                            [1] = "clock",
                            [2] = "coverdeck",
                            [3] = "quote",
                            [4] = "reading_goals",
                            [5] = "reading_stats",
                        },
                    },
                },
            },
            ["simpleui_navbar_transparent"] = false,
            ["simpleui_qa_row_instances"] = {},
            ["simpleui_reading_goals_layout"] = "compact",
            ["simpleui_reading_goals_show_annual"] = false,
            ["simpleui_reading_goals_show_daily"] = true,
            ["simpleui_reading_goals_show_monthly"] = false,
            ["simpleui_statusbar_transparent"] = false,
            ["simpleui_style_progress_bar_type"] = "framed",
            ["simpleui_style_wallpaper_enabled"] = false,
            ["simpleui_style_wallpaper_opacity"] = 0,
            ["simpleui_wallpaper_show_in_fm"] = false,
        },
    },
    ["simpleui_hs_quick_actions_1_enabled"] = false,
    ["simpleui_hs_quick_actions_1_items"] = {
        [1] = "bookmark_browser",
    },
    ["simpleui_hs_quick_actions_2_enabled"] = false,
    ["simpleui_hs_quick_actions_3_enabled"] = false,
    ["simpleui_hs_quote_align"] = "center",
    ["simpleui_hs_quote_enabled"] = false,
    ["simpleui_hs_quote_scale"] = 100,
    ["simpleui_hs_quote_source"] = "quotes",
    ["simpleui_hs_reading_goals"] = false,
    ["simpleui_hs_reading_goals_elem_order"] = {
        [1] = "annual",
        [2] = "monthly",
        [3] = "daily",
    },
    ["simpleui_hs_reading_goals_enabled"] = false,
    ["simpleui_hs_reading_goals_scale"] = 90,
    ["simpleui_hs_reading_goals_show_frame"] = false,
    ["simpleui_hs_reading_goals_solid_bg"] = false,
    ["simpleui_hs_reading_stats_enabled"] = true,
    ["simpleui_hs_reading_stats_items"] = {
        [1] = "today_time",
        [2] = "today_pages",
        [3] = "total_time",
    },
    ["simpleui_hs_reading_stats_scale"] = 50,
    ["simpleui_hs_reading_stats_type"] = "list",
    ["simpleui_hs_recent"] = true,
    ["simpleui_hs_recent_enabled"] = false,
    ["simpleui_hs_recent_progress_style"] = "bar_text",
    ["simpleui_hs_recent_show_finished"] = true,
    ["simpleui_hs_recent_show_frame"] = true,
    ["simpleui_hs_recent_show_overlay"] = false,
    ["simpleui_hs_recent_show_progress"] = true,
    ["simpleui_hs_recent_show_text"] = true,
    ["simpleui_hs_recent_solid_bg"] = false,
    ["simpleui_hs_return_on_wakeup"] = false,
    ["simpleui_hs_simpleui_quote_align"] = "center",
    ["simpleui_hs_simpleui_quote_fixed_height"] = true,
    ["simpleui_hs_simpleui_quote_source"] = "highlights",
    ["simpleui_hs_tbr_enabled"] = false,
    ["simpleui_layout"] = {
        ["pages"] = {
            [1] = {
                ["id"] = 1,
                ["modules"] = {
                    [1] = "coverdeck",
                    [2] = "reading_stats",
                },
            },
        },
    },
    ["simpleui_loaded_version"] = "2.7.0",
    ["simpleui_navbar_transparent"] = false,
    ["simpleui_onboarding_done"] = true,
    ["simpleui_preserve_deleted_books_in_stats"] = false,
    ["simpleui_qa_list"] = {},
    ["simpleui_qa_migrated_v1"] = true,
    ["simpleui_qa_row_instances"] = {},
    ["simpleui_qs_bar_bg"] = "flat",
    ["simpleui_qs_bar_enabled"] = false,
    ["simpleui_qs_bar_frontlight"] = true,
    ["simpleui_qs_bar_settings_on_hold"] = true,
    ["simpleui_qs_bar_shape"] = "round",
    ["simpleui_qs_bar_slots"] = {
        [1] = "night_mode",
    },
    ["simpleui_qs_bar_warmth"] = false,
    ["simpleui_quote_deck_count"] = 99,
    ["simpleui_quote_deck_order"] = "5,69,57,82,29,21,26,75,65,13,11,95,35,66,79,76,23,61,86,24,50,6,42,44,62,25,85,88,4,55,98,22,40,17,54,64,9,3,84,80,60,48,49,74,83,18,56,94,96,2,52,45,16,39,47,38,8,32,41,87,15,27,53,33,73,97,67,30,51,71,1,19,92,93,91,78,10,46,14,89,28,77,36,63,58,72,31,12,81,68,34,90,20,70,43,59,37,99,7",
    ["simpleui_quote_deck_pos"] = 22,
    ["simpleui_quote_hl_deck_count"] = 4,
    ["simpleui_quote_hl_deck_order"] = "2,4,1,3",
    ["simpleui_quote_hl_deck_pos"] = 1,
    ["simpleui_reading_goal"] = 2,
    ["simpleui_reading_goals_layout"] = "compact",
    ["simpleui_reading_goals_show_annual"] = false,
    ["simpleui_reading_goals_show_daily"] = true,
    ["simpleui_reading_goals_show_monthly"] = false,
    ["simpleui_settings_migrated_v2"] = true,
    ["simpleui_settings_migrated_v3"] = true,
    ["simpleui_settings_migrated_v4"] = true,
    ["simpleui_settings_migrated_v5"] = true,
    ["simpleui_settings_migrated_v6"] = true,
    ["simpleui_settings_migrated_v7"] = true,
    ["simpleui_settings_migrated_v8"] = true,
    ["simpleui_settings_tab_enabled"] = true,
    ["simpleui_stale_books_v1"] = {
        ["prefetched_data"] = {
            ["/mnt/us/BOOKS/14个王朝的最后10年 [纯净版].epub"] = {
                ["authors"] = "冯敏飞",
                ["doc_pages"] = 209,
                ["partial_md5_checksum"] = "deaf1b94032667edc0df4740f7abb946",
                ["percent"] = 0.0095693779904306,
                ["stat_pages"] = 209,
                ["summary"] = {
                    ["modified"] = "2026-08-23",
                    ["status"] = "reading",
                },
                ["title"] = "14个王朝的最后10年",
            },
            ["/mnt/us/BOOKS/[三联][插图]书剑恩仇录 - 金庸.EPUB"] = {
                ["authors"] = "金庸",
                ["doc_pages"] = 1865,
                ["partial_md5_checksum"] = "0826022763d5995e07a0ce5d3d6e5892",
                ["percent"] = 0.014477211796247,
                ["stat_pages"] = 1865,
                ["summary"] = {
                    ["modified"] = "2026-08-25",
                    ["status"] = "reading",
                },
                ["title"] = "[三联][插图]书剑恩仇录",
            },
            ["/mnt/us/BOOKS/【精品汇-343】基督山伯爵全3册插图版 (大仲马) (z-library.sk, 1lib.sk, z-lib.sk).mobi"] = {
                ["authors"] = "大仲马",
                ["doc_pages"] = 3717,
                ["partial_md5_checksum"] = "047fccb53f28f1b3a4241c2f8cd0bd63",
                ["percent"] = 0.0016142050040355,
                ["stat_pages"] = 3717,
                ["summary"] = {
                    ["modified"] = "2026-08-27",
                    ["status"] = "reading",
                },
                ["title"] = "【精品汇-343】基督山伯爵全3册插图版",
            },
            ["/mnt/us/BOOKS/一人之下 14 (裁边版).cbz"] = {
                ["authors"] = "米二",
                ["doc_pages"] = 215,
                ["partial_md5_checksum"] = "d4218ad6cac08280e790d50b74f7d038",
                ["percent"] = 0.0093023255813953,
                ["stat_pages"] = 215,
                ["summary"] = {
                    ["modified"] = "2026-08-29",
                    ["status"] = "reading",
                },
                ["title"] = "一人之下 14",
            },
            ["/mnt/us/BOOKS/一人之下 5 (裁边版).cbz"] = {
                ["authors"] = "米二",
                ["doc_pages"] = 225,
                ["partial_md5_checksum"] = "a2f6e9e148f4ce68ea98a29150711067",
                ["percent"] = 0.031111111111111,
                ["stat_pages"] = 225,
                ["summary"] = {
                    ["modified"] = "2026-08-27",
                    ["status"] = "reading",
                },
                ["title"] = "一人之下 5",
            },
            ["/mnt/us/BOOKS/乡土中国（果麦经典） [纯净版].epub"] = {
                ["authors"] = "费孝通",
                ["doc_pages"] = 77,
                ["partial_md5_checksum"] = "573beae306cf3a0a54d6c7bf0ce90835",
                ["percent"] = 0.4025974025974,
                ["stat_pages"] = 77,
                ["summary"] = {
                    ["modified"] = "2026-08-27",
                    ["status"] = "reading",
                },
                ["title"] = "乡土中国（果麦经典）",
            },
            ["/mnt/us/BOOKS/六祖坛经 - 惠能.EPUB"] = {
                ["authors"] = "惠能",
                ["doc_pages"] = 253,
                ["partial_md5_checksum"] = "845a095d6843a1b3d821efb66e4ef1ad",
                ["percent"] = 0.071146245059289,
                ["stat_pages"] = 253,
                ["summary"] = {
                    ["modified"] = "2026-08-30",
                    ["status"] = "reading",
                },
                ["title"] = "六祖坛经",
            },
            ["/mnt/us/BOOKS/南明史（全2册） [纯净版].epub"] = {
                ["authors"] = "顾诚",
                ["doc_pages"] = 366,
                ["partial_md5_checksum"] = "0b2fb6f440dbe247bf105cfc11908ae2",
                ["percent"] = 0.19398907103825,
                ["stat_pages"] = 366,
                ["summary"] = {
                    ["modified"] = "2026-08-23",
                    ["status"] = "reading",
                },
                ["title"] = "南明史（全2册）",
            },
            ["/mnt/us/BOOKS/平凡的世界 (路遥) (z-library.sk, 1lib.sk, z-lib.sk).epub"] = {
                ["authors"] = "路遥",
                ["doc_pages"] = 4308,
                ["partial_md5_checksum"] = "53e542e8f0659a930cbb0432069b6363",
                ["percent"] = 0.00023212627669452,
                ["stat_pages"] = 4308,
                ["summary"] = {
                    ["modified"] = "2026-08-29",
                    ["status"] = "reading",
                },
                ["title"] = "平凡的世界（激励亿万读者的新课标经典、改变马云一生的书、新晋男神朱一龙推荐）",
            },
            ["/mnt/us/BOOKS/我的前半生 [纯净版].epub"] = {
                ["authors"] = "[清]爱新觉罗·溥仪",
                ["doc_pages"] = 1844,
                ["partial_md5_checksum"] = "9393889345b56bb8eb606bbedf42042a",
                ["percent"] = 0.68167028199566,
                ["stat_pages"] = 1844,
                ["summary"] = {
                    ["modified"] = "2026-08-23",
                    ["status"] = "reading",
                },
                ["title"] = "我的前半生",
            },
            ["/mnt/us/BOOKS/战犯改造所见闻 (沈醉回忆录) - 沈醉.EPUB"] = {
                ["authors"] = "沈醉",
                ["doc_pages"] = 1312,
                ["partial_md5_checksum"] = "59ed3fa7b6774ac5a06b912dac0038d4",
                ["percent"] = 0.080030487804878,
                ["stat_pages"] = 1312,
                ["summary"] = {
                    ["modified"] = "2026-08-27",
                    ["status"] = "reading",
                },
                ["title"] = "战犯改造所见闻 （沈醉回忆录）(一部记录中国历史上未曾有过的、也永不再现的特殊影像的史料图书。)",
            },
            ["/mnt/us/BOOKS/棋魂·光之棋 - 05卷 - 堀田由美, 小畑健.EPUB"] = {
                ["authors"] = "堀田由美, 小畑健",
                ["doc_pages"] = 203,
                ["partial_md5_checksum"] = "a9c8f04170317f0e5b0bcddc47b278ec",
                ["percent"] = 0.029556650246305,
                ["stat_pages"] = 203,
                ["summary"] = {
                    ["modified"] = "2026-08-30",
                    ["status"] = "reading",
                },
                ["title"] = "棋魂 - 05卷 - 堀田由美, 小畑健",
            },
            ["/mnt/us/BOOKS/沈醉回忆录：我的特务生涯（一个军统特务的忏悔录） [纯净版].epub"] = {
                ["authors"] = "沈醉口述 沈美娟整理",
                ["doc_pages"] = 152,
                ["partial_md5_checksum"] = "e2e39b83c7c9885b30f901e5cbfb4171",
                ["percent"] = 0.052631578947368,
                ["stat_pages"] = 152,
                ["summary"] = {
                    ["modified"] = "2026-08-23",
                    ["status"] = "reading",
                },
                ["title"] = "沈醉回忆录：我的特务生涯（一个军统特务的忏悔录）",
            },
            ["/mnt/us/BOOKS/翦商：殷周之变与华夏新生 [纯净版].epub"] = {
                ["authors"] = "李硕",
                ["doc_pages"] = 1686,
                ["partial_md5_checksum"] = "2c35f3b53d9acef4b6d3ad2486bc468e",
                ["percent"] = 0.062870699881376,
                ["stat_pages"] = 1686,
                ["summary"] = {
                    ["modified"] = "2026-08-23",
                    ["status"] = "reading",
                },
                ["title"] = "翦商：殷周之变与华夏新生",
            },
            ["/mnt/us/BOOKS/鸳鸯刀（轻经典） [纯净版].epub"] = {
                ["authors"] = "金庸",
                ["doc_pages"] = 197,
                ["partial_md5_checksum"] = "b4618c9fcb3634bbe0b46866379d0bb4",
                ["percent"] = 0.11675126903553,
                ["stat_pages"] = 197,
                ["summary"] = {
                    ["modified"] = "2026-08-30",
                    ["status"] = "reading",
                },
                ["title"] = "鸳鸯刀（轻经典）",
            },
        },
        ["recent_fps"] = {
            [1] = "/mnt/us/BOOKS/我的前半生 [纯净版].epub",
            [2] = "/mnt/us/BOOKS/战犯改造所见闻 (沈醉回忆录) - 沈醉.EPUB",
            [3] = "/mnt/us/BOOKS/南明史（全2册） [纯净版].epub",
            [4] = "/mnt/us/BOOKS/鸳鸯刀（轻经典） [纯净版].epub",
            [5] = "/mnt/us/BOOKS/六祖坛经 - 惠能.EPUB",
            [6] = "/mnt/us/BOOKS/棋魂·光之棋 - 05卷 - 堀田由美, 小畑健.EPUB",
            [7] = "/mnt/us/BOOKS/14个王朝的最后10年 [纯净版].epub",
            [8] = "/mnt/us/BOOKS/一人之下 14 (裁边版).cbz",
            [9] = "/mnt/us/BOOKS/平凡的世界 (路遥) (z-library.sk, 1lib.sk, z-lib.sk).epub",
            [10] = "/mnt/us/BOOKS/翦商：殷周之变与华夏新生 [纯净版].epub",
            [11] = "/mnt/us/BOOKS/沈醉回忆录：我的特务生涯（一个军统特务的忏悔录） [纯净版].epub",
            [12] = "/mnt/us/BOOKS/【精品汇-343】基督山伯爵全3册插图版 (大仲马) (z-library.sk, 1lib.sk, z-lib.sk).mobi",
            [13] = "/mnt/us/BOOKS/一人之下 5 (裁边版).cbz",
            [14] = "/mnt/us/BOOKS/[三联][插图]书剑恩仇录 - 金庸.EPUB",
            [15] = "/mnt/us/BOOKS/乡土中国（果麦经典） [纯净版].epub",
        },
    },
    ["simpleui_stale_stats_v1"] = {
        ["avg_pages"] = 0,
        ["avg_secs"] = 0,
        ["books_total"] = 0,
        ["books_year"] = 0,
        ["db_conn_fatal"] = false,
        ["month_pages"] = 0,
        ["month_secs"] = 0,
        ["streak"] = 0,
        ["today_pages"] = 0,
        ["today_secs"] = 0,
        ["total_secs"] = 0,
        ["week_pages"] = 0,
        ["week_secs"] = 0,
        ["year_secs"] = 0,
    },
    ["simpleui_stats_loading_notice"] = false,
    ["simpleui_statusbar_transparent"] = false,
    ["simpleui_streak_freeze_last_total_secs"] = 8994,
    ["simpleui_streak_freeze_time_secs"] = 3067,
    ["simpleui_streak_freeze_watermark"] = 3,
    ["simpleui_streak_mode"] = "real",
    ["simpleui_style_progress_bar_type"] = "flat",
    ["simpleui_style_wallpaper"] = "./settings/simpleui/sui_wallpapers/wallpaper1.png",
    ["simpleui_style_wallpaper_enabled"] = true,
    ["simpleui_style_wallpaper_opacity"] = 0,
    ["simpleui_tb_custom"] = true,
    ["simpleui_tb_fm_cfg"] = {
        ["order_left"] = {
            [1] = "fm_back",
            [2] = "fm_search",
            [3] = "up_button",
            [4] = "search_button",
        },
        ["order_right"] = {
            [1] = "fm_browse",
            [2] = "fm_menu",
            [3] = "browse_button",
            [4] = "menu_button",
        },
        ["side"] = {
            ["fm_back"] = "left",
            ["fm_browse"] = "right",
            ["fm_menu"] = "right",
            ["fm_search"] = "left",
        },
    },
    ["simpleui_tb_item_fm_browse"] = true,
    ["simpleui_tb_item_fm_search"] = true,
    ["simpleui_tb_size_pct"] = "default",
    ["simpleui_tbr_list"] = {
        [1] = "/mnt/us/BOOKS/我的前半生 [纯净版].epub",
        [2] = "/mnt/us/BOOKS/洪业：清朝开国史 [纯净版].epub",
        [3] = "/mnt/us/BOOKS/14个王朝的最后10年 [纯净版].epub",
        [4] = "/mnt/us/BOOKS/草原帝国 [纯净版].epub",
        [5] = "/mnt/us/BOOKS/战犯改造所见闻 (沈醉回忆录) - 沈醉.EPUB",
    },
    ["simpleui_topbar_config"] = {
        ["order"] = {},
        ["order_center"] = {},
        ["order_left"] = {
            [1] = "clock",
        },
        ["order_right"] = {
            [1] = "wifi",
            [2] = "battery",
            [3] = "disk",
        },
        ["show"] = {},
        ["side"] = {
            ["battery"] = "right",
            ["clock"] = "left",
            ["disk"] = "hidden",
            ["wifi"] = "right",
        },
    },
    ["simpleui_topbar_enabled"] = false,
    ["simpleui_topbar_wifi_hide_when_off"] = true,
    ["simpleui_ui_font_enabled"] = true,
    ["simpleui_ui_font_name"] = "HYKongShanKai",
    ["simpleui_updater_auto_check"] = false,
    ["simpleui_wallpaper_show_in_fm"] = false,
}
